import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import { Marketplace } from '../components/Marketplace'
import { useEffect, useState } from 'react'
// import abi
export default function Home() {
  // console.log(process.env);
  const [account, setAccount] = useState(null)
  useEffect(() => {
    setAccount(window.ethereum.selectedAddress)
  }, [])
  // const abi = 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-primary w-screen '>
        <section className='w-full h-screen'>
          <Navbar setAccount={setAccount} account={account}/>
          <div className='intro'>

          </div>
        </section>
        <section className='marketplace w-full  py-8 bg-primary'>
            <h1 className='text-5xl text-center  text-white'>Explore Latest NFTs</h1>
            <div className='w-full h-screen my-4 px-8'> 
            <Marketplace/>
            </div>
        </section>
      </main>
    </div>
  )
}
